const ORDER_ONPROGRESS = 'ONPROGRESS';
const ORDER_COMPLETED = 'COMPLETED';

const PAYMENT_TYPE_LINKAJA = 'LINKAJA';
const PAYMENT_TYPE_QUOTA = 'QUOTA';

module.exports = {
  ORDER_ONPROGRESS,
  ORDER_COMPLETED,
  PAYMENT_TYPE_LINKAJA,
  PAYMENT_TYPE_QUOTA,
};
